#!/bin/sh
set -eu

staged_files=$(git diff --cached --name-only --diff-filter=ACM -- '*.py' '*.swift')

if [ -n "$staged_files" ]; then
    repo_root=$(git rev-parse --show-toplevel)
    echo "$staged_files" | sed "s|^|$repo_root/|" | xargs "$repo_root/format.sh"
    echo "$staged_files" | xargs git add
fi
