#!/bin/sh
set -eu

staged_py_files=$(git diff --cached --name-only --diff-filter=ACM -- 'server/*.py')

if [ -n "$staged_py_files" ]; then
    (cd server && uv run ruff format -- $(echo "$staged_py_files" | sed 's|^server/||'))
    (cd server && uv run ruff check --fix -- $(echo "$staged_py_files" | sed 's|^server/||'))
    echo "$staged_py_files" | xargs git add
fi

staged_swift_files=$(git diff --cached --name-only --diff-filter=ACM -- 'ios/*.swift')

if [ -n "$staged_swift_files" ]; then
    echo "$staged_swift_files" | xargs xcrun swift-format format --in-place
    echo "$staged_swift_files" | xargs git add
fi
